var select = document.querySelector('p');
console.log(select);
var select1 = document.querySelectorAll('p');
console.log(select1);
var select2 = document.querySelector('.answer-1');
console.log(select2);
var select3 = document.querySelectorAll('.answer-1');
console.log(select3);
var select4 = document.getElementsByClassName('answer-1');
console.log(select4);
